version: "3.8"

services:
  postfix:
    build: .
    container_name: postfix
    hostname: mail.typingsprint.com
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
